config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  get "dashboard/index"

  resources :data_uploads
  resources :microgrid_configs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/data_upload.rb
class DataUpload < ApplicationRecord
  has_one_attached :file
end

app/models/microgrid_config.rb
class MicrogridConfig < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dashboard_controller.rb
# app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  require 'csv'
  require 'time'

  def index
    # --- Przetwarzanie pliku z danymi obciążenia (Load Data) ---
    load_upload = DataUpload.find_by(file_type: 'load')
    if load_upload.present? && load_upload.file.attached?
      load_csv = CSV.parse(load_upload.file.download, headers: true)
      time_header = load_csv.headers.include?("time") ? "time" : "_time"
      @times_load  = load_csv[time_header].map { |t| Time.parse(t) }
      @load_values = load_csv["Load (kW)"].map(&:to_f)
    else
      flash.now[:alert] = "Nie znaleziono pliku z danymi obciążenia. Proszę przesłać plik."
      @times_load  = []
      @load_values = []
    end

    # --- Przetwarzanie pliku z danymi ceny i PV (Price and PV Data) ---
    price_upload = DataUpload.find_by(file_type: 'price_panel')
    if price_upload.present? && price_upload.file.attached?
      price_csv = CSV.parse(price_upload.file.download, headers: true)
      time_header_price = price_csv.headers.include?("time") ? "time" : "_time"
      @times_price   = price_csv[time_header_price].map { |t| Time.parse(t) }
      @energy_prices = price_csv["Energy price (PLN/MWh)"].map(&:to_f)
      @pv_generation = price_csv["PV_3MW_generation (kWh)"].map(&:to_f)
    else
      flash.now[:alert] = "Nie znaleziono pliku z danymi ceny/PV. Proszę przesłać plik."
      @times_price   = []
      @energy_prices = []
      @pv_generation = []
    end

    # --- Gwarancja, że zmienne są zawsze ustawione ---
    @times_load   ||= []
    @load_values  ||= []
    @times_price  ||= []
    @energy_prices||= []
    @pv_generation||= []
  end
end

app/controllers/data_uploads_controller.rb
class DataUploadsController < ApplicationController
  before_action :set_data_upload, only: %i[ show edit update destroy ]

  # GET /data_uploads or /data_uploads.json
  def index
    @data_uploads = DataUpload.all
  end

  # GET /data_uploads/1 or /data_uploads/1.json
  def show
  end

  # GET /data_uploads/new
  def new
    @data_upload = DataUpload.new
  end

  # GET /data_uploads/1/edit
  def edit
  end

  # POST /data_uploads or /data_uploads.json
  def create
    @data_upload = DataUpload.new(data_upload_params)

    respond_to do |format|
      if @data_upload.save
        format.html { redirect_to @data_upload, notice: "Data upload was successfully created." }
        format.json { render :show, status: :created, location: @data_upload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @data_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_uploads/1 or /data_uploads/1.json
  def update
    respond_to do |format|
      if @data_upload.update(data_upload_params)
        format.html { redirect_to @data_upload, notice: "Data upload was successfully updated." }
        format.json { render :show, status: :ok, location: @data_upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @data_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_uploads/1 or /data_uploads/1.json
  def destroy
    @data_upload.destroy!

    respond_to do |format|
      format.html { redirect_to data_uploads_path, status: :see_other, notice: "Data upload was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_data_upload
    # Use params[:id] or params.require(:id) – the important part is to access the ID correctly.
    @data_upload = DataUpload.find(params[:id])
  end

  def data_upload_params
    # Permit file_type along with name and file.
    params.require(:data_upload).permit(:name, :file, :file_type)
  end
end

app/controllers/microgrid_configs_controller.rb
class MicrogridConfigsController < ApplicationController
  before_action :set_microgrid_config, only: %i[ show edit update destroy ]

  # GET /microgrid_configs or /microgrid_configs.json
  def index
    @microgrid_configs = MicrogridConfig.all
  end

  # GET /microgrid_configs/1 or /microgrid_configs/1.json
  def show
  end

  # GET /microgrid_configs/new
  def new
    @microgrid_config = MicrogridConfig.new
  end

  # GET /microgrid_configs/1/edit
  def edit
  end

  # POST /microgrid_configs or /microgrid_configs.json
  def create
    @microgrid_config = MicrogridConfig.new(microgrid_config_params)

    respond_to do |format|
      if @microgrid_config.save
        format.html { redirect_to @microgrid_config, notice: "Microgrid config was successfully created." }
        format.json { render :show, status: :created, location: @microgrid_config }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @microgrid_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microgrid_configs/1 or /microgrid_configs/1.json
  def update
    respond_to do |format|
      if @microgrid_config.update(microgrid_config_params)
        format.html { redirect_to @microgrid_config, notice: "Microgrid config was successfully updated." }
        format.json { render :show, status: :ok, location: @microgrid_config }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @microgrid_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microgrid_configs/1 or /microgrid_configs/1.json
  def destroy
    @microgrid_config.destroy!

    respond_to do |format|
      format.html { redirect_to microgrid_configs_path, status: :see_other, notice: "Microgrid config was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_microgrid_config
      @microgrid_config = MicrogridConfig.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def microgrid_config_params
      params.expect(microgrid_config: [ :load_flexibility, :battery_capacity, :ev_charging_power ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/data_uploads_helper.rb
module DataUploadsHelper
end

app/helpers/microgrid_configs_helper.rb
module MicrogridConfigsHelper
end

app/views/dashboard/index.html.erb
<!-- app/views/dashboard/index.html.erb -->
<h1>Dashboard Microgrid</h1>

<div class="section">
  <h2>Dane Obciążenia (Load Data)</h2>
  <% load_data = @times_load.zip(@load_values).to_h %>
  <%= line_chart load_data, xtitle: "Czas", ytitle: "Obciążenie (kW)" %>
</div>

<div class="section">
  <h2>Dane Cen i Generacji PV (Price and PV Data)</h2>
  <% price_data = @times_price.zip(@energy_prices).to_h %>
  <%= line_chart price_data, xtitle: "Czas", ytitle: "Cena Energii (PLN/MWh)" %>

  <% pv_data = @times_price.zip(@pv_generation).to_h %>
  <%= line_chart pv_data, xtitle: "Czas", ytitle: "Generacja PV (kWh)" %>
</div>
<h1>Testowy wykres</h1>
<%= line_chart({ "2024-01-01" => 5, "2024-01-02" => 10, "2024-01-03" => 7 }) %>

app/views/data_uploads/_data_upload.html.erb
<div id="<%= dom_id data_upload %>">
  <p>
    <strong>Name:</strong>
    <%= data_upload.name %>
  </p>

  <p>
    <strong>File:</strong>
    <%= link_to data_upload.file.filename, data_upload.file if data_upload.file.attached? %>
  </p>

</div>

app/views/data_uploads/_form.html.erb
<%= form_with(model: data_upload) do |form| %>
  <% if data_upload.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(data_upload.errors.count, "error") %> prohibited this data_upload from being saved:</h2>

      <ul>
        <% data_upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file_type, "Typ pliku" %>
    <%= form.select :file_type, options_for_select([['Obiazenie', 'load'], ['Cena i PV', 'price_panel']]) %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/data_uploads/edit.html.erb
<% content_for :title, "Editing data upload" %>

<h1>Editing data upload</h1>

<%= render "form", data_upload: @data_upload %>

<br>

<div>
  <%= link_to "Show this data upload", @data_upload %> |
  <%= link_to "Back to data uploads", data_uploads_path %>
</div>

app/views/data_uploads/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Data uploads" %>

<h1>Data uploads</h1>

<div id="data_uploads">
  <% @data_uploads.each do |data_upload| %>
    <%= render data_upload %>
    <p>
      <%= link_to "Show this data upload", data_upload %>
    </p>
  <% end %>
</div>

<%= link_to "New data upload", new_data_upload_path %>

app/views/data_uploads/new.html.erb
<% content_for :title, "New data upload" %>

<h1>New data upload</h1>

<%= render "form", data_upload: @data_upload %>

<br>

<div>
  <%= link_to "Back to data uploads", data_uploads_path %>
</div>

app/views/data_uploads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @data_upload %>

<div>
  <%= link_to "Edit this data upload", edit_data_upload_path(@data_upload) %> |
  <%= link_to "Back to data uploads", data_uploads_path %>

  <%= button_to "Destroy this data upload", @data_upload, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hackatron" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microgrid_configs/_form.html.erb
<%= form_with(model: microgrid_config) do |form| %>
  <% if microgrid_config.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(microgrid_config.errors.count, "error") %> prohibited this microgrid_config from being saved:</h2>

      <ul>
        <% microgrid_config.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :load_flexibility, style: "display: block" %>
    <%= form.text_field :load_flexibility %>
  </div>

  <div>
    <%= form.label :battery_capacity, style: "display: block" %>
    <%= form.text_field :battery_capacity %>
  </div>

  <div>
    <%= form.label :ev_charging_power, style: "display: block" %>
    <%= form.number_field :ev_charging_power %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microgrid_configs/_microgrid_config.html.erb
<div id="<%= dom_id microgrid_config %>">
  <p>
    <strong>Load flexibility:</strong>
    <%= microgrid_config.load_flexibility %>
  </p>

  <p>
    <strong>Battery capacity:</strong>
    <%= microgrid_config.battery_capacity %>
  </p>

  <p>
    <strong>Ev charging power:</strong>
    <%= microgrid_config.ev_charging_power %>
  </p>

</div>

app/views/microgrid_configs/edit.html.erb
<% content_for :title, "Editing microgrid config" %>

<h1>Editing microgrid config</h1>

<%= render "form", microgrid_config: @microgrid_config %>

<br>

<div>
  <%= link_to "Show this microgrid config", @microgrid_config %> |
  <%= link_to "Back to microgrid configs", microgrid_configs_path %>
</div>

app/views/microgrid_configs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Microgrid configs" %>

<h1>Microgrid configs</h1>

<div id="microgrid_configs">
  <% @microgrid_configs.each do |microgrid_config| %>
    <%= render microgrid_config %>
    <p>
      <%= link_to "Show this microgrid config", microgrid_config %>
    </p>
  <% end %>
</div>

<%= link_to "New microgrid config", new_microgrid_config_path %>

app/views/microgrid_configs/new.html.erb
<% content_for :title, "New microgrid config" %>

<h1>New microgrid config</h1>

<%= render "form", microgrid_config: @microgrid_config %>

<br>

<div>
  <%= link_to "Back to microgrid configs", microgrid_configs_path %>
</div>

app/views/microgrid_configs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @microgrid_config %>

<div>
  <%= link_to "Edit this microgrid config", edit_microgrid_config_path(@microgrid_config) %> |
  <%= link_to "Back to microgrid configs", microgrid_configs_path %>

  <%= button_to "Destroy this microgrid config", @microgrid_config, method: :delete %>
</div>